In [1]:
from Prismatic_Delta import Prismatic_Delta
from DeltaArray import DeltaArray

import time
from serial import Serial
import math
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d
from time import sleep
import linear_actuator_pb2

In [3]:
s_p = 1.5 #side length of the platform
s_b = 4.3 #side length of the base
l = 4.5 #length of leg attached to platform

Delta = Prismatic_Delta(s_p, s_b, l)
thetas = np.linspace(0, 2*np.pi, 36)

r = 1

In [4]:
for theta in thetas:
    # for z in zvals:
    ee_pts = [r*np.cos(theta), r*np.sin(theta), 10.0]
    pts = Delta.IK(ee_pts)
    pts = np.array(pts) * 0.01
    print(theta)
    print(pts)

0.0
[0.05921193 0.05591296 0.06280233]
0.17951958020513104
[0.05851028 0.056293   0.0631313 ]
0.35903916041026207
[0.0578423  0.05676795 0.0633296 ]
0.5385587406153931
[0.0572274  0.05732544 0.06338871]
0.7180783208205241
[0.0566827  0.05795044 0.06330606]
0.8975979010256552
[0.05622278 0.05862544 0.06308523]
1.0771174812307862
[0.05585957 0.05933067 0.0627357 ]
1.2566370614359172
[0.05560227 0.06004446 0.06227208]
1.4361566416410483
[0.05545725 0.0607437  0.06171311]
1.6156762218461793
[0.05542807 0.06140454 0.06108042]
1.7951958020513104
[0.05551543 0.06200321 0.06039738]
1.9747153822564414
[0.05571722 0.06251706 0.05968791]
2.1542349624615724
[0.05602844 0.06292575 0.05897559]
2.3337545426667035
[0.05644133 0.06321245 0.05828287]
2.5132741228718345
[0.0569453  0.06336502 0.05763054]
2.6927937030769655
[0.05752709 0.06337686 0.05703726]
2.8723132832820966
[0.05817082 0.06324745 0.05651932]
3.0518328634872276
[0.05885819 0.0629824  0.05609045]
3.2313524436923586
[0.05956876 0.06259298